- name: Update yum cache
  yum:
    update_cache: yes
  become: yes

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Add Docker repository
  shell: |
    yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker-CE
  yum:
    name: docker-ce
    state: present
  become: yes

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Download Docker Compose
  shell: curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

- name: Verify Docker Compose installation
  command: docker compose --version
  register: docker_compose_version_output
  changed_when: false

- name: Display Docker Compose version
  debug:
    msg: "Docker Compose version: {{ docker_compose_version_output.stdout }}"

